# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blake Larson, PE, PhD
email: git@blakelarson.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website, with links to my interests and projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blakelarson.github.io" # the base hostname & protocol for your site
twitter_username: blake_larson
github_username:  blakelarson

# Build settings
markdown: kramdown
